import { test, expect } from '@playwright/test'

/**
 * AL — Alert Toast System
 *
 * AL-01: Alert toast appears when a thermal or voltage violation is triggered.
 *
 * Violations are generated by the backend ViolationScanner on every powerflow
 * solve.  We force a violation by decommitting a generator — the backend runs a
 * powerflow after the command and, if overloads are detected, emits alerts in
 * the next GameStateUpdate DELTA.
 *
 * @see docs/ux/03-alert-toasts.md
 * @see issue #85 (component), #210 (this test)
 */

interface AlertDto {
  id: string
  severity: string
  elementId: string | null
  message: string
}

interface StoreSnapshot {
  network: {
    generators: Array<{ id: string; committed: boolean; maxActivePowerMw: number }>
  } | null
  alerts: AlertDto[]
  sendCommand: (msg: { commandType: string; payload: Record<string, unknown> }) => void
}

declare global {
  interface Window {
    __e2e: { getStore: () => StoreSnapshot }
  }
}

// Discover the highest-capacity committed generator from a throwaway session so
// decommitting it is most likely to produce a violation.
let targetGenId: string

test.beforeAll(async ({ request }) => {
  const tokenRes = await request.post('/api/auth/token', { data: {} })
  const { token } = await tokenRes.json() as { token: string }

  const sessionRes = await request.post('/api/sessions', {
    data: { displayName: 'AL discovery', mode: 'FREE_PLAY', networkPreset: 'ieee14' },
    headers: { Authorization: `Bearer ${token}` },
  })
  const { id } = await sessionRes.json() as { id: string }

  const networkRes = await request.get(`/api/sessions/${id}/network`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  const network = await networkRes.json() as {
    generators: Array<{ id: string; connected: boolean; maxActivePowerMw: number }>
  }

  // Pick the committed generator with the largest capacity — most likely to trigger
  // overloads on adjacent branches when decommitted.
  const committed = network.generators.filter((g) => g.connected)
  committed.sort((a, b) => b.maxActivePowerMw - a.maxActivePowerMw)
  targetGenId = committed[0]?.id ?? ''

  await request.delete(`/api/sessions/${id}`, { headers: { Authorization: `Bearer ${token}` } })
  expect(targetGenId).toBeTruthy()
})

test('AL-01 decommitting a large generator triggers a visible alert toast', async ({ page }) => {
  await page.goto('/')

  // Wait for session bootstrap to complete
  await page.waitForSelector('[data-testid="bootstrap-overlay"]', {
    state: 'hidden',
    timeout: 15_000,
  })

  // Wait for the first game tick so the store has live network data
  await page.waitForFunction(
    () => (window.__e2e?.getStore().network?.generators?.length ?? 0) > 0,
    { timeout: 15_000 },
  )

  // No alerts should be present at game start
  const container = page.getByTestId('alert-toast-container')
  await expect(container).not.toBeVisible()

  // Decommit the largest generator — this triggers a backend powerflow that
  // should produce at least one thermal or convergence alert.
  await page.evaluate(
    (id) =>
      window.__e2e
        .getStore()
        .sendCommand({ commandType: 'DecommitGenerator', payload: { generatorId: id } }),
    targetGenId,
  )

  // Wait for the backend to broadcast a DELTA with at least one alert
  await page.waitForFunction(
    () => (window.__e2e?.getStore().alerts?.length ?? 0) > 0,
    { timeout: 20_000 },
  )

  // AlertToastContainer must be visible and contain at least one toast card
  await expect(container).toBeVisible({ timeout: 5_000 })

  // At least one individual toast must be present in the DOM
  const toasts = page.locator('[data-testid^="toast-"]')
  expect(await toasts.count()).toBeGreaterThan(0)
})
