import '../../shared/e2e-bridge'
import { test, expect } from '@playwright/test'

/**
 * AL — Alert Toast System
 *
 * AL-01: Alert toast appears when a thermal or voltage violation is triggered.
 *
 * Violations are generated by the backend ViolationScanner on every powerflow
 * solve.  We force a violation by decommitting the largest committed generator —
 * the backend runs a powerflow after the command and, if overloads are detected,
 * emits alerts in the next GameStateUpdate DELTA.
 *
 * Generator selection is done from the live Zustand store via the __e2e bridge.
 * We wait for `tickNumber > 0` to ensure the first WebSocket FULL update has
 * arrived — the initial REST network hydration uses the domain model (`connected`)
 * while the WS update uses the frontend DTO (`committed`).
 *
 * @see docs/ux/03-alert-toasts.md
 * @see issue #85 (component), #210 (this test)
 */

test('AL-01 decommitting a large generator triggers a visible alert toast', async ({ page }) => {
  await page.goto('/')

  // Wait for session bootstrap to complete
  await page.waitForSelector('[data-testid="bootstrap-overlay"]', {
    state: 'hidden',
    timeout: 15_000,
  })

  // Wait for the first WebSocket FULL update AND for at least one generator to
  // have `committed === true`.  Checking tickNumber > 0 alone is not sufficient:
  // in CI the REST hydration response can arrive *after* the first WS tick and
  // overwrite network with the domain model (which uses `connected`, not `committed`).
  // The source-level race is fixed in useGameStore.connect(), but we keep an
  // explicit `committed` check here as a belt-and-suspenders guard.
  await page.waitForFunction(
    () => {
      const s = window.__e2e?.getStore()
      return (
        s !== undefined &&
        (s.tickNumber ?? 0) > 0 &&
        (s.network?.generators ?? []).some((g) => g.committed === true)
      )
    },
    { timeout: 20_000 },
  )

  // No alerts should be present at game start
  const container = page.getByTestId('alert-toast-container')
  await expect(container).not.toBeVisible()

  // Pick the committed generator with the largest capacity from the live store.
  // Decommitting it is most likely to produce a thermal overload on adjacent branches.
  const targetGenId = await page.evaluate(() => {
    const generators = window.__e2e.getStore().network?.generators ?? []
    const committed = generators.filter((g) => g.committed)
    committed.sort((a, b) => b.maxActivePowerMw - a.maxActivePowerMw)
    return committed[0]?.id ?? null
  })

  if (!targetGenId) throw new Error('No committed generators found after WS tick — check ieee14 preset')

  // Decommit — this triggers a backend powerflow that should produce violations
  await page.evaluate(
    (id) =>
      window.__e2e
        .getStore()
        .sendCommand({ commandType: 'DecommitGenerator', payload: { generatorId: id } }),
    targetGenId,
  )

  // Wait for the backend to broadcast a DELTA with at least one alert.
  // 20 s matches the mutation-response window used in other command tests (cm.spec.ts).
  await page.waitForFunction(
    () => (window.__e2e?.getStore().alerts?.length ?? 0) > 0,
    { timeout: 20_000 },
  )

  // AlertToastContainer must be visible
  await expect(container).toBeVisible({ timeout: 5_000 })

  // At least one individual toast card must be rendered
  const toasts = page.locator('[data-testid^="toast-"]')
  expect(await toasts.count()).toBeGreaterThan(0)
})
