package com.gridmaster.game.event

import com.gridmaster.engine.model.FuelType
import com.gridmaster.engine.model.NetworkMutation

// ─────────────────────────────────────────────────────────────────────────────
// GameEvent hierarchy
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Base type for all dynamic environment events generated by the [EventEngine].
 *
 * Each event category has meaningfully different fields, so we use a sealed
 * hierarchy rather than a flat type with nullable fields. This makes event
 * handling exhaustive and type-safe in `when` expressions.
 */
sealed class GameEvent {
    abstract val id: String
    abstract val category: EventCategory
    abstract val description: String
    abstract val severity: EventSeverity
    /** Direct effects produced when this event fires. PolicyEvent always returns an empty list; card option effects are applied on resolution. */
    abstract val effects: List<EventEffect>
}

enum class EventCategory { WEATHER, ECONOMIC, POLICY, FUEL }

enum class EventSeverity { INFO, WARNING, CRITICAL }

// ── Weather ──────────────────────────────────────────────────────────────────

data class WeatherEvent(
    override val id: String,
    override val category: EventCategory = EventCategory.WEATHER,
    override val description: String,
    override val severity: EventSeverity,
    val type: WeatherEventType,
    /** Null or empty = system-wide; non-empty = only these regions are affected. */
    val affectedRegionIds: List<String>?,
    val durationMinutes: Int,
    override val effects: List<EventEffect>,
) : GameEvent()

enum class WeatherEventType {
    STORM,
    HEAT_WAVE,
    HIGH_WIND,
    COLD_SNAP,
}

// ── Economic ─────────────────────────────────────────────────────────────────

data class EconomicEvent(
    override val id: String,
    override val category: EventCategory = EventCategory.ECONOMIC,
    override val description: String,
    override val severity: EventSeverity,
    val type: EconomicEventType,
    val durationMinutes: Int,
    override val effects: List<EventEffect>,
) : GameEvent()

enum class EconomicEventType {
    GDP_GROWTH,
    RECESSION,
    HOLIDAY,
    INDUSTRIAL_BOOM,
    EV_ADOPTION_SURGE,
}

// ── Policy ───────────────────────────────────────────────────────────────────

data class PolicyEvent(
    override val id: String,
    override val category: EventCategory = EventCategory.POLICY,
    override val description: String,
    override val severity: EventSeverity,
    /** The decision card the player must respond to. */
    val card: EventCard,
    /** Always empty — effects come from [CardOption.effects] resolved via [EventEngine.resolveCard]. */
    override val effects: List<EventEffect> = emptyList(),
) : GameEvent()

// ── Fuel ─────────────────────────────────────────────────────────────────────

data class FuelEvent(
    override val id: String,
    override val category: EventCategory = EventCategory.FUEL,
    override val description: String,
    override val severity: EventSeverity,
    val type: FuelEventType,
    /** Informational — the fuel type targeted by this event. The actual effect is encoded in [effects]. */
    val affectedFuelType: FuelType,
    val durationMinutes: Int,
    override val effects: List<EventEffect>,
) : GameEvent()

enum class FuelEventType { PRICE_SPIKE, SUPPLY_DISRUPTION, PRICE_COLLAPSE }

// ─────────────────────────────────────────────────────────────────────────────
// Event effects
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A concrete, serialisable effect produced by a [GameEvent].
 *
 * Effects are data, not callbacks — they can be persisted in the event log,
 * replayed deterministically, and tested in isolation. The [EventEngine]
 * converts effects to [NetworkMutation]s using the current network snapshot.
 */
sealed class EventEffect {
    /**
     * Immediately disconnect [elementId] (line or generator).
     * Produces [NetworkMutation.TripLine] or [NetworkMutation.TripGenerator].
     */
    data class TripElement(val elementId: String) : EventEffect()

    /**
     * Reduce [elementId]'s current thermal rating to [ratingFactor] × its nominal value.
     * Stored as an active effect modifier; does not produce a network mutation directly.
     */
    data class DerateElement(
        val elementId: String,
        val ratingFactor: Double,
    ) : EventEffect()

    /**
     * Scale load in [regionIds] by [factor]. Null or empty = system-wide.
     * Produces [NetworkMutation.SetLoadPower] for each affected load.
     */
    data class ScaleLoad(
        val regionIds: List<String>?,
        val factor: Double,
    ) : EventEffect()

    /**
     * Multiply marginalCostPerMwh of generators with [fuelType] by [factor].
     * Stored as an active cost modifier; does not produce a network mutation.
     */
    data class ScaleGeneratorCost(
        val fuelType: FuelType,
        val factor: Double,
    ) : EventEffect()
}

// ─────────────────────────────────────────────────────────────────────────────
// Player decision card
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A decision card surfaced to the player when a [PolicyEvent] fires.
 * The player must choose one [CardOption] before the simulation advances.
 */
data class EventCard(
    /** Unique identifier used to look up this card in [EventEngine.resolveCard]. */
    val cardId: String = java.util.UUID.randomUUID().toString(),
    val prompt: String,
    val options: List<CardOption>,
)

/**
 * One option in an [EventCard].
 *
 * @param label Short label displayed on the option button.
 * @param effects Effects applied to the session if this option is chosen.
 * @param costGbp One-time cost charged to the player's budget (default 0).
 */
data class CardOption(
    val label: String,
    val effects: List<EventEffect>,
    val costGbp: Double = 0.0,
    /**
     * How long duration-based effect modifiers from this option last (game-minutes).
     * Null = permanent (never expires).
     */
    val durationMinutes: Int? = null,
)

// ─────────────────────────────────────────────────────────────────────────────
// Fired event
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The result of an event firing during a tick.
 *
 * @param mutations Immediate [NetworkMutation]s ready to apply to the IIDM network.
 * @param card Non-null when a player decision is required (PolicyEvent).
 * @param expiresAtGameTimeMinutes When to reverse duration-based effect modifiers (null = permanent).
 */
data class FiredEvent(
    val event: GameEvent,
    val firedAtGameTimeMinutes: Long,
    val mutations: List<NetworkMutation>,
    val card: EventCard?,
    val expiresAtGameTimeMinutes: Long?,
)

// ─────────────────────────────────────────────────────────────────────────────
// Stochastic configuration
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Configuration for the per-session Poisson event generators in Free Play mode.
 *
 * @param randomSeed Null = random; non-null = deterministic replay (Challenge / Tutorial).
 */
data class EventConfig(
    val weatherMeanInterArrivalMinutes: Int = 720,
    val economicMeanInterArrivalMinutes: Int = 4320,
    val policyMeanInterArrivalMinutes: Int = 14400,
    val fuelMeanInterArrivalMinutes: Int = 7200,
    val randomSeed: Long? = null,
)
