package com.gridmaster.api.websocket

import com.gridmaster.engine.powerflow.PowerFlowResult
import com.gridmaster.game.WeatherState
import com.gridmaster.game.command.Alert
import com.gridmaster.game.event.EventCard

/**
 * Publishes game state to all subscribed WebSocket clients for a session.
 *
 * Called from [com.gridmaster.game.TickEngineImpl] at Step 8 of each tick,
 * and from [CommandWebSocketController] after a command is processed.
 *
 * Implementations track per-session state to decide between FULL and DELTA
 * messages, keeping bandwidth low at high simulation speeds.
 */
interface GameStatePublisher {
    companion object {
        /** Send a FULL update every this many ticks (in addition to on connect/reconnect). */
        const val FULL_STATE_INTERVAL_TICKS = 30L
    }

    /**
     * Publish a state update after a tick completes.
     *
     * The implementation decides FULL vs DELTA based on [tickNumber] and whether
     * tracked state has changed since the last broadcast.
     *
     * @param sessionId    Target session.
     * @param tickNumber   Current tick counter (1-based).
     * @param gameTimeMinutes  Accumulated game-time minutes.
     * @param powerFlowResult  Result of the tick's power flow solve.
     * @param newAlerts    Alerts generated by events this tick.
     * @param pendingCards Pending event cards awaiting player response.
     */
    fun publishTick(
        sessionId: String,
        tickNumber: Long,
        gameTimeMinutes: Long,
        clockState: com.gridmaster.game.ClockState,
        clockSpeedMultiplier: Int,
        powerFlowResult: PowerFlowResult,
        newAlerts: List<Alert>,
        pendingCards: List<EventCard>,
        healthScore: Int? = null,
        tutorialStep: Int? = null,
        challengeTimeRemainingMinutes: Int? = null,
        /** Current simulated weather (issue #391); null if weather is disabled. See [com.gridmaster.game.WeatherSimulator]. */
        weatherState: WeatherState? = null,
        weatherCloudCoverPct: Double? = null,
        weatherWindSpeedMps: Double? = null,
        weatherRegionId: String? = null,
    )

    /**
     * Publish a FULL state update immediately — used on client connect/reconnect
     * and after commands that change network state.
     *
     * @param missedTicks Non-null on reconnect; included in [ConnectionStatus].
     */
    fun publishFull(
        sessionId: String,
        tickNumber: Long,
        gameTimeMinutes: Long,
        clockState: com.gridmaster.game.ClockState,
        clockSpeedMultiplier: Int,
        powerFlowResult: PowerFlowResult,
        newAlerts: List<Alert>,
        pendingCards: List<EventCard>,
        missedTicks: Long? = null,
        /** Current simulated weather (issue #391); null if weather is disabled or unavailable. */
        weatherState: WeatherState? = null,
        weatherCloudCoverPct: Double? = null,
        weatherWindSpeedMps: Double? = null,
        weatherRegionId: String? = null,
    )

    /**
     * Publish a GAME_OVER lifecycle message to all subscribers of [sessionId].
     *
     * Called by [com.gridmaster.game.TickEngineImpl] when the game-over condition is met.
     */
    fun publishGameOver(
        sessionId: String,
        dto: GameOverDto,
    )

    /**
     * Remove all tracked state for [sessionId] when the session is stopped or deleted.
     */
    fun clearSession(sessionId: String)
}

